import { expect, test } from "@playwright/test"

test.describe("Silver production homepage", () => {
  test("indexable content, current prices and nonce-protected scripts", async ({ page }) => {
    const errors: string[] = []
    page.on("pageerror", error => { errors.push(error.message) })
    const response = await page.goto("/")
    expect(response?.status()).toBe(200)
    expect(response?.headers()["content-security-policy"]).toContain("strict-dynamic")
    await expect(page.locator("h1")).toContainText("Vaša firma.")
    await expect(page.locator('meta[name="robots"]')).toHaveAttribute("content", "index, follow")
    await expect(page.locator('link[rel="canonical"]')).toHaveAttribute("href", "https://www.codera.sk/")
    await expect(page.locator('.offer')).toHaveCount(2)
    await expect(page.locator('.offer').first()).toContainText("499 €")
    await expect(page.locator('.offer').last()).toContainText("699 €")
    await expect(page.locator('#motion-toggle')).toBeVisible()
    expect(await page.locator('script[src]').evaluateAll(nodes => nodes.every(n => Boolean((n as HTMLScriptElement).nonce)))).toBe(true)
    expect(await page.locator('script[type="application/ld+json"]').allTextContents()).toHaveLength(2)
    expect(errors).toEqual([])
  })
  test("complete portfolio without decorative labels", async ({ page }) => {
    await page.goto("/")
    await expect(page.locator('.project')).toHaveCount(5)
    await expect(page.locator('.project .concept,.project-caption')).toHaveCount(0)
    await page.locator('.project').first().evaluate(el=>el.scrollIntoView({block:'start'}))
    await page.locator('.project-preview').first().click()
    await expect(page.locator('.project-dialog')).toBeVisible()
    await expect.poll(() => page.locator('#preview-image').evaluate(el => (el as HTMLImageElement).naturalWidth)).toBe(2880)
    await page.keyboard.press('Escape')
    await expect(page.locator('.project-dialog')).not.toBeVisible()
    await expect(page.locator('.project-preview').first()).toBeFocused()
  })
  test("navigation, disclosures and contact validation", async ({ page }) => {
    await page.goto('/')
    const hrefs=await page.locator('a[href^="#"]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('href')).filter((h):h is string=>!!h&&h.length>1))
    for(const href of new Set(hrefs))await expect(page.locator(href)).toHaveCount(1)
    await page.locator('.offer summary').first().click()
    await expect(page.locator('.offer-details').first()).toHaveAttribute('open','')
    expect(await page.locator('#dopyt').evaluate(el=>(el as HTMLFormElement).checkValidity())).toBe(false)
    await expect(page.locator('.footer-wordmark img')).toHaveAttribute('src','/brand/codera-wordmark-display.svg')
  })
  test("mobile and reduced-motion content", async ({ page }) => {
    await page.emulateMedia({reducedMotion:'reduce'})
    await page.setViewportSize({width:390,height:844})
    const videos: string[]=[]
    page.on('request',r=>{if(r.url().endsWith('.mp4'))videos.push(r.url())})
    await page.goto('/')
    await expect(page.locator('h1')).toBeVisible()
    await page.locator('.menu-button').click()
    await page.locator('#mobile-menu a[href="#praca"]').click()
    await expect(page.locator('#mobile-menu')).not.toBeVisible()
    expect(videos).toEqual([])
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    expect(await page.locator('.project').first().evaluate(el=>getComputedStyle(el).position)).toBe('relative')
  })
  test("content and SEO without JavaScript", async ({ browser, request }) => {
    const page=await browser.newPage({javaScriptEnabled:false})
    await page.goto('/')
    await expect(page.locator('h1')).toBeVisible()
    await expect(page.locator('.offer')).toHaveCount(2)
    await expect(page.locator('a[href="mailto:kontakt@codera.sk"]').first()).toBeVisible()
    expect((await request.get('/robots.txt')).ok()).toBe(true)
    expect((await request.get('/sitemap.xml')).ok()).toBe(true)
    await page.close()
  })
  test("demo navigation back to the HTML homepage", async ({ page }) => {
    await page.goto('/ukazky/wordpress')
    const home=page.locator('a[href="/"]').first()
    await expect(home).toBeVisible()
    await home.click()
    await expect(page.locator('h1')).toContainText('Vaša firma.')
    await expect(page.locator('#motion-toggle')).toBeVisible()
  })
})
