/* generated by scratchpad/build-asm5.js from the traced element polygons -
   positions are percent of the 16:9 frame, delays in seconds */
export type AsmKind = "rock" | "building" | "bridge"
export interface AsmElement {
  id: string
  kind: AsmKind
  floors: number
  delay: number
  left: number
  top: number
  width: number
}
export const ASM_ELEMENTS: readonly AsmElement[] = [
  { id: "r1", kind: "rock", floors: 10, delay: 0, left: 22.266, top: 49.583, width: 29.896 },
  { id: "r2", kind: "rock", floors: 10, delay: 0, left: 48.255, top: 51.574, width: 25.99 },
  { id: "r3", kind: "rock", floors: 10, delay: 0, left: 69.245, top: 49.583, width: 30.755 },
  { id: "bfar", kind: "building", floors: 11, delay: 1.88, left: 93.047, top: 21.852, width: 6.953 },
  { id: "btall", kind: "building", floors: 14, delay: 1.32, left: 58.958, top: 4.491, width: 9.297 },
  { id: "bpink", kind: "building", floors: 11, delay: 1.54, left: 41.563, top: 23.38, width: 9.271 },
  { id: "bpeach", kind: "building", floors: 9, delay: 1.66, left: 30.651, top: 36.25, width: 12.292 },
  { id: "blcyl", kind: "building", floors: 5, delay: 2, left: 25.964, top: 54.352, width: 10.885 },
  { id: "bcenter", kind: "building", floors: 9, delay: 1.2, left: 52.057, top: 30.556, width: 21.589 },
  { id: "brtowers", kind: "building", floors: 12, delay: 1.77, left: 79.948, top: 28.75, width: 11.901 },
  { id: "brcyl", kind: "building", floors: 5, delay: 2.1, left: 79.245, top: 62.778, width: 15.391 },
  { id: "bridges", kind: "bridge", floors: 0, delay: 3.5, left: 37.161, top: 36.343, width: 47.891 },
]
