/* generated by scratchpad/build-asm4.js from the traced element polygons -
   positions are percent of the 16:9 frame, delays in seconds */
export type AsmKind = "rock" | "building" | "bridge"
export interface AsmElement {
  id: string
  kind: AsmKind
  floors: number
  delay: number
  left: number
  top: number
  width: number
}
export const ASM_ELEMENTS: readonly AsmElement[] = [
  { id: "r1", kind: "rock", floors: 0, delay: 0.14, left: 21.693, top: 49.167, width: 31.615 },
  { id: "r2", kind: "rock", floors: 0, delay: 0, left: 47.682, top: 51.157, width: 27.135 },
  { id: "r3", kind: "rock", floors: 0, delay: 0.28, left: 68.698, top: 49.167, width: 31.302 },
  { id: "bfar", kind: "building", floors: 9, delay: 1.05, left: 92.5, top: 21.481, width: 7.5 },
  { id: "btall", kind: "building", floors: 12, delay: 0.7, left: 58.385, top: 2.685, width: 10.625 },
  { id: "bpink", kind: "building", floors: 9, delay: 0.85, left: 40.599, top: 22.5, width: 10.807 },
  { id: "bpeach", kind: "building", floors: 8, delay: 0.95, left: 30.078, top: 35.88, width: 13.438 },
  { id: "blcyl", kind: "building", floors: 4, delay: 1.1, left: 25.391, top: 53.981, width: 12.031 },
  { id: "bcenter", kind: "building", floors: 7, delay: 0.8, left: 51.484, top: 30.185, width: 22.734 },
  { id: "brtowers", kind: "building", floors: 10, delay: 0.95, left: 79.375, top: 28.194, width: 13.047 },
  { id: "brcyl", kind: "building", floors: 4, delay: 1.15, left: 78.698, top: 62.361, width: 16.51 },
  { id: "bridges", kind: "bridge", floors: 0, delay: 2, left: 36.589, top: 35.972, width: 49.036 },
]
