/* generated by scratchpad/build-live.js from the traced element polygons -
   positions are percent of the 16:9 frame; a group moves as one block */
export type LiveGroup = "left" | "centre" | "right" | "bridges"
export interface LiveElement {
  id: string
  group: LiveGroup
  left: number
  top: number
  width: number
  /** width / height of the picture, so a box can be sized without loading it */
  ratio: number
}
export const LIVE_ELEMENTS: readonly LiveElement[] = [
  { id: "r1", group: "left", left: 22.266, top: 49.583, width: 30.469, ratio: 1.3589 },
  { id: "r2", group: "centre", left: 48.255, top: 51.574, width: 25.99, ratio: 1.104 },
  { id: "r3", group: "right", left: 69.245, top: 49.583, width: 30.755, ratio: 1.0845 },
  { id: "bfar", group: "right", left: 93.047, top: 21.852, width: 6.953, ratio: 0.1764 },
  { id: "btall", group: "centre", left: 58.958, top: 4.491, width: 9.297, ratio: 0.4301 },
  { id: "bpink", group: "left", left: 41.146, top: 23.38, width: 9.688, ratio: 0.4869 },
  { id: "bpeach", group: "left", left: 30.651, top: 36.25, width: 12.292, ratio: 0.7003 },
  { id: "blcyl", group: "left", left: 25.964, top: 54.352, width: 10.885, ratio: 1.4564 },
  { id: "bcenter", group: "centre", left: 52.057, top: 30.556, width: 21.589, ratio: 1.0402 },
  { id: "brtowers", group: "right", left: 79.948, top: 28.75, width: 11.901, ratio: 0.5844 },
  { id: "brcyl", group: "right", left: 79.245, top: 62.778, width: 15.391, ratio: 1.3371 },
  { id: "bridges", group: "bridges", left: 37.161, top: 36.343, width: 47.891, ratio: 2.2024 },
]
